version: "2.4"
services:
  rabbitmq:
    image: rabbitmq:management-alpine
  redis:
    image: redis:alpine
  pokedex:
    image: favware/graphql-pokemon:latest
  postgres:
    build: ./postgres
    image: skyrabot/postgres:latest
  lavalink:
    build: ./lavalink
    image: skyrabot/lavalink:latest
