name: test

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v2
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.101
      - run: dotnet test Skyra.Tests
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: true
